language: node_js
services:
- rabbitmq
node_js:
- '0.10'
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
before_script:
- mosquitto -d
- npm install -g grunt-cli
script:
- npm test
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: StmXxkIR+mp8lNbTEAX6mnhXg0o8+iIHhHGJaiLRSdb1swVcp70SpftPVMnbH2Sg5KE37m5M2MSeY7OWqLe0cOHHMnBYK+cKIw9fbUrRAohhHLzWfu5rQtndnCAN2EfIGXNwTQpTKWdnqjT557ZwVr+itWJnSS2E7xswXPhVcQ4=
  on:
    tags: true
    repo: noflo/noflo-runtime-msgflo
